# Generated by Django 5.1.7 on 2026-09-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='accepts_quotes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='business',
            name='weekly_capacity',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
