# Generated by Django 5.1.7 on 2026-09-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('businesses', '0002_business_accepts_quotes_business_weekly_capacity')]
    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('monthly_price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('limits', models.JSONField(default=dict, help_text='Límites: orders, public_products, users, storage_mb, quote_responses')),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('trial', 'Prueba'), ('suspended', 'Suspendida'), ('cancelled', 'Cancelada')], default='active', max_length=12)),
                ('starts_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='businesses.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='businesses.plan')),
            ],
        ),
    ]
