# Generated by Django 5.1.7 on 2026-09-15 04:37

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_accepts_quotes_business_weekly_capacity'),
        ('operations', '0002_product_moderation_status_featuredbusiness_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('client', 'Cliente'), ('business', 'Empresa')], max_length=10)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='operations.conversation')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuoteProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('production_days', models.PositiveSmallIntegerField()),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('materials', models.CharField(blank=True, max_length=240)),
                ('technique', models.CharField(blank=True, max_length=100)),
                ('payment_terms', models.CharField(blank=True, max_length=240)),
                ('deposit_percentage', models.PositiveSmallIntegerField(default=50)),
                ('valid_until', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('viewed', 'Vista'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('expired', 'Vencida'), ('withdrawn', 'Retirada')], default='sent', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_proposals', to='businesses.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('total_price', 'production_days'),
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='operations.quoteproposal'),
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(max_length=100)),
                ('product_type', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('approximate_budget', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('region', models.CharField(max_length=100)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('delivery_method', models.CharField(default='shipping', max_length=20)),
                ('delivery_scope', models.CharField(blank=True, max_length=30)),
                ('contact_name', models.CharField(max_length=160)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('proposals', 'Con propuestas'), ('accepted', 'Aceptada'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_for', to='operations.quoteproposal')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='quoteproposal',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='operations.quoterequest'),
        ),
        migrations.CreateModel(
            name='QuoteMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('reasons', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_matches', to='businesses.business')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='operations.quoterequest')),
            ],
            options={
                'ordering': ('-score', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='quoteproposal',
            constraint=models.UniqueConstraint(fields=('request', 'business'), name='unique_proposal_per_business'),
        ),
        migrations.AddConstraint(
            model_name='quotematch',
            constraint=models.UniqueConstraint(fields=('request', 'business'), name='unique_quote_match'),
        ),
    ]
