# Generated by Django 5.1.7 on 2026-09-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies=[('businesses','0003_plan_subscription'),('operations','0004_designapproval_designchangerequest_orderfile'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[migrations.CreateModel(name='AuditLog',fields=[
        ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),
        ('action',models.CharField(max_length=80)),('entity_type',models.CharField(max_length=80)),('entity_id',models.CharField(blank=True,max_length=80)),('metadata',models.JSONField(blank=True,default=dict)),('ip_address',models.GenericIPAddressField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),
        ('actor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='audit_logs',to=settings.AUTH_USER_MODEL)),
        ('business',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='audit_logs',to='businesses.business')),
    ],options={'ordering':('-created_at',)})]
