# Generated by Django 5.1.7 on 2026-09-15
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies=[('businesses','0003_plan_subscription'),('operations','0005_auditlog'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[migrations.CreateModel(name='Notification',fields=[
        ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('kind',models.CharField(max_length=40)),('title',models.CharField(max_length=160)),('body',models.CharField(blank=True,max_length=300)),('url',models.CharField(blank=True,max_length=240)),('read_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),
        ('business',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='notifications',to='businesses.business')),('recipient',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='notifications',to=settings.AUTH_USER_MODEL)),
    ],options={'ordering':('-created_at',)})]
