# Generated by Django 5.1.7 on 2026-09-16
import uuid
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies=[('operations','0006_notification')]
    operations=[migrations.AddField(model_name='quoterequest',name='access_token',field=models.UUIDField(default=uuid.uuid4,editable=False,unique=True))]
