# Generated by Django 5.1.7 on 2026-09-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_plan_subscription'),
        ('operations', '0009_message_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/gallery/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('size', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='businesses.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='operations.product')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
    ]
