# Generated by Django 5.1.7 on 2026-09-21 02:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_plan_subscription'),
        ('operations', '0011_order_public_access_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business', 'is_active'], name='customer_business_active_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business', 'phone'], name='customer_business_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business', 'email'], name='customer_business_email_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['business', 'recipient', 'read_at', '-created_at'], name='notification_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'status', 'due_date'], name='order_tenant_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'created_at'], name='order_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'payment_status'], name='order_tenant_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'is_active', 'is_public'], name='product_tenant_visibility_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_public', 'moderation_status', 'is_active', 'created_at'], name='product_marketplace_idx'),
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['status', 'created_at'], name='quote_status_created_idx'),
        ),
    ]
