import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import api,{apiError} from '../api'
import {clp} from '../utils'
type Activity={id:number;action:string;business:string;actor:string;created_at:string}
type Metrics={businesses:number;active_businesses:number;users:number;public_products:number;pending_products:number;quote_requests:number;orders:number;accepted_quotes:number;recent_activity:Activity[]}
type Company={id:number;name:string;slug:string;email:string;region:string;status:string;is_verified:boolean;users_count:number;products_count:number}
type ModerationProduct={id:number;name:string;business:string;category:string;sale_price:string;moderation_status:string}
type Featured={businesses:Array<{target_id:number}>;products:Array<{target_id:number}>}
const labels:Record<string,string>={pending:'Pendiente',active:'Activa',suspended:'Suspendida',rejected:'Rechazada',approved:'Aprobado',hidden:'Oculto'}
const actions:Record<string,string>={'platform.business_updated':'Empresa actualizada','platform.product_moderated':'Producto moderado','product.created':'Producto creado','product.updated':'Producto actualizado','order.created':'Pedido creado','order.public_requested':'Solicitud desde tienda','order.status_changed':'Estado de pedido actualizado','payment.recorded':'Pago registrado','quote.proposal_sent':'Propuesta enviada','quote.proposal_accepted':'Propuesta aceptada','design.approval_link_created':'Enlace de aprobación creado','design.approval_link_revoked':'Enlace de aprobación revocado','design.approved':'Diseño aprobado','design.changes_requested':'Cambios solicitados','order.file_uploaded':'Archivo cargado'}
export default function AdminDashboard(){
 const cache=useQueryClient();const refresh=()=>{cache.invalidateQueries({queryKey:['platform-businesses']});cache.invalidateQueries({queryKey:['platform-products']});cache.invalidateQueries({queryKey:['platform-metrics']})}
 const metrics=useQuery({queryKey:['platform-metrics'],queryFn:async()=>{const {data}=await api.get<Metrics>('/platform/dashboard/');return data}})
 const businesses=useQuery({queryKey:['platform-businesses'],queryFn:async()=>{const {data}=await api.get<Company[]>('/platform/businesses/');return data}})
 const products=useQuery({queryKey:['platform-products'],queryFn:async()=>{const {data}=await api.get<ModerationProduct[]>('/platform/products/');return data}})
 const featured=useQuery({queryKey:['platform-featured'],queryFn:async()=>{const {data}=await api.get<Featured>('/platform/featured/');return data}})
 const companyMutation=useMutation({mutationFn:({id,data}:{id:number;data:Partial<Company>})=>api.patch(`/platform/businesses/${id}/`,data),onSuccess:refresh})
 const productMutation=useMutation({mutationFn:({id,status}:{id:number;status:string})=>api.patch(`/platform/products/${id}/`,{moderation_status:status}),onSuccess:refresh})
 const featuredMutation=useMutation({mutationFn:({kind,target_id}:{kind:'business'|'product';target_id:number})=>api.post('/platform/featured/',{kind,target_id}),onSuccess:()=>{cache.invalidateQueries({queryKey:['platform-featured']});cache.invalidateQueries({queryKey:['platform-metrics']})}})
 const error=metrics.error||businesses.error||products.error||featured.error||companyMutation.error||productMutation.error||featuredMutation.error;const m=metrics.data
 const featuredBusinesses=new Set(featured.data?.businesses.map(item=>item.target_id));const featuredProducts=new Set(featured.data?.products.map(item=>item.target_id))
 return <div className="platform-page"><div className="page-head"><div><span className="eyebrow">Control de plataforma</span><h1>Resumen de EstampaFlow</h1><p>Empresas, catálogo público y actividad del marketplace.</p></div></div>{error&&<div className="alert alert-danger mt-3">{apiError(error)}</div>}
 <section className="platform-metrics">{m&&[['Empresas',m.businesses,'shop'],['Activas',m.active_businesses,'check-circle'],['Usuarios',m.users,'people'],['Productos públicos',m.public_products,'boxes'],['Por moderar',m.pending_products,'hourglass-split'],['Pedidos',m.orders,'receipt'],['Solicitudes',m.quote_requests,'chat-square-text'],['Cotizaciones aceptadas',m.accepted_quotes,'trophy']].map(([label,value,icon])=><div className="metric" key={String(label)}><span className="metric-icon bg-primary"><i className={`bi bi-${icon}`}/></span><div><small>{label}</small><strong>{value}</strong></div></div>)}</section>
 <section className="panel mt-4"><div className="section-title"><div><h2>Empresas</h2><p>Activa, suspende, verifica y destaca emprendimientos.</p></div><span>{businesses.data?.length||0} registros</span></div><div className="table-responsive"><table className="table align-middle"><thead><tr><th>Empresa</th><th>Estado</th><th>Actividad</th><th>Verificación</th><th>Acciones</th></tr></thead><tbody>{businesses.data?.map(b=><tr key={b.id}><td><strong>{b.name} {featuredBusinesses.has(b.id)&&<i className="bi bi-star-fill text-warning"/>}</strong><small>{b.email||b.slug} · {b.region||'Sin región'}</small></td><td><span className={`status-pill ${b.status}`}>{labels[b.status]||b.status}</span></td><td>{b.products_count} productos · {b.users_count} usuarios</td><td>{b.is_verified?<span className="text-success"><i className="bi bi-patch-check-fill"/> Verificada</span>:'Pendiente'}</td><td><div className="admin-actions"><button onClick={()=>companyMutation.mutate({id:b.id,data:{is_verified:!b.is_verified}})}>{b.is_verified?'Quitar verificación':'Verificar'}</button><button onClick={()=>featuredMutation.mutate({kind:'business',target_id:b.id})}>{featuredBusinesses.has(b.id)?'Retirar destaque':'Destacar'}</button>{b.status==='active'?<button className="danger" onClick={()=>companyMutation.mutate({id:b.id,data:{status:'suspended'}})}>Suspender</button>:<button onClick={()=>companyMutation.mutate({id:b.id,data:{status:'active'}})}>Activar</button>}</div></td></tr>)}</tbody></table></div></section>
 <section className="panel mt-4"><div className="section-title"><div><h2>Moderación de productos</h2><p>Solo los productos aprobados aparecen en el marketplace.</p></div></div><div className="table-responsive"><table className="table align-middle"><thead><tr><th>Producto</th><th>Empresa</th><th>Precio</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{products.data?.map(p=><tr key={p.id}><td><strong>{p.name} {featuredProducts.has(p.id)&&<i className="bi bi-star-fill text-warning"/>}</strong><small>{p.category}</small></td><td>{p.business}</td><td>{clp(p.sale_price)}</td><td><span className={`status-pill ${p.moderation_status}`}>{labels[p.moderation_status]}</span></td><td><div className="admin-actions"><button onClick={()=>productMutation.mutate({id:p.id,status:'approved'})}>Aprobar</button>{p.moderation_status==='approved'&&<button onClick={()=>featuredMutation.mutate({kind:'product',target_id:p.id})}>{featuredProducts.has(p.id)?'Retirar destaque':'Destacar'}</button>}<button onClick={()=>productMutation.mutate({id:p.id,status:'hidden'})}>Ocultar</button><button className="danger" onClick={()=>productMutation.mutate({id:p.id,status:'rejected'})}>Rechazar</button></div></td></tr>)}</tbody></table></div></section>
 <section className="panel mt-4"><div className="section-title"><div><h2>Actividad reciente</h2><p>Registro histórico de acciones importantes.</p></div></div><div className="audit-list">{m?.recent_activity.length?m.recent_activity.map(item=><div key={item.id}><span className="audit-icon"><i className="bi bi-clock-history"/></span><div><strong>{actions[item.action]||item.action}</strong><small>{item.business} · {item.actor}</small></div><time>{new Intl.DateTimeFormat('es-CL',{dateStyle:'short',timeStyle:'short'}).format(new Date(item.created_at))}</time></div>):<p className="text-muted mb-0">Las acciones importantes aparecerán aquí.</p>}</div></section></div>
}
