import {useQuery} from '@tanstack/react-query'
import api from '../api'
import type {Order,Payment} from '../types'
import {chileDate,clp} from '../utils'
import {PageHead} from './Customers'
type Proposal={id:number;request_title:string;total_price:string;status:string;valid_until:string}
type Item={id:number;title:string;detail:string;amount:string;url:string}
export default function Documents(){const orders=useQuery({queryKey:['orders','documents'],queryFn:async()=>{const {data}=await api.get('/orders/',{params:{page_size:100}});return data.results as Order[]}});const proposals=useQuery({queryKey:['quote-proposals','documents'],queryFn:async()=>{const {data}=await api.get('/quote-proposals/',{params:{page_size:100}});return data.results as Proposal[]}});const payments=useQuery({queryKey:['payments','documents'],queryFn:async()=>{const {data}=await api.get('/payments/',{params:{page_size:100}});return data.results as Payment[]}});return <><PageHead title="Documentos" text="Descarga fichas, propuestas y comprobantes imprimibles."/><div className="document-grid"><DocumentPanel title="Fichas de producción" icon="printer" empty="No hay pedidos." items={orders.data?.map(order=>({id:order.id,title:order.display_number,detail:`${order.customer_name} · ${chileDate(order.due_date)}`,amount:clp(order.total),url:`/orders/${order.id}/pdf/`}))}/><DocumentPanel title="Propuestas" icon="file-earmark-text" empty="No hay propuestas enviadas." items={proposals.data?.map(item=>({id:item.id,title:item.request_title,detail:`Válida hasta ${chileDate(item.valid_until)}`,amount:clp(item.total_price),url:`/quote-proposals/${item.id}/pdf/`}))}/><DocumentPanel title="Comprobantes de pago" icon="cash-coin" empty="No hay pagos registrados." items={payments.data?.map(item=>({id:item.id,title:`Pago #${item.id}`,detail:new Date(item.paid_at).toLocaleString('es-CL'),amount:clp(item.amount),url:`/payments/${item.id}/pdf/`}))}/></div></>}
function DocumentPanel({title,icon,items,empty}:{title:string;icon:string;items?:Item[];empty:string}){return <section className="panel document-panel"><header><span><i className={`bi bi-${icon}`}/></span><h2>{title}</h2></header>{items?.length?items.map(item=><div className="document-row" key={item.id}><div><strong>{item.title}</strong><small>{item.detail}</small></div><b>{item.amount}</b><a className="btn btn-sm btn-outline-primary" href={`${api.defaults.baseURL}${item.url}`} target="_blank"><i className="bi bi-download"/> PDF</a></div>):<p className="text-muted">{empty}</p>}</section>}
