from django.contrib import admin
from .models import AuditLog,Conversation,Customer,DesignApproval,DesignChangeRequest,FeaturedBusiness,FeaturedProduct,Message,Notification,Order,OrderFile,OrderItem,OrderStatusHistory,Payment,Product,ProductCategory,ProductVariant,QuoteMatch,QuoteProposal,QuoteRequest
admin.site.register((Customer,ProductCategory,Product,ProductVariant,Order,OrderItem,OrderStatusHistory,Payment,FeaturedBusiness,FeaturedProduct,QuoteRequest,QuoteMatch,QuoteProposal,Conversation,Message,OrderFile,DesignApproval,DesignChangeRequest,AuditLog,Notification))
